name: Reusable Basic Test Job

on:
  workflow_call:
    inputs:
      test_command:
        required: true
        type: string
      install_python:
        required: false
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: kaiachain/build_base:go1.23.7-solc0.8.13-ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: setup python 3.9
        if: ${{ inputs.install_python == true }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Download dev branch
        run: |
          git config --global --add safe.directory /__w/kaia/kaia
          git fetch origin dev:dev
          apt-get install netcat-traditional
      - name: Wait for Redis
        run: |
          for i in $(seq 1 10); do
            nc -z 127.0.0.1 6379 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Redis && exit 1
        continue-on-error: true
      - name: Wait for Kafka
        run: |
          for i in $(seq 1 10); do
            nc -z kafka 9092 && echo Success && exit 0
            echo -n .
            sleep 1
          done
          echo Failed waiting for Kafka && exit 1
        continue-on-error: true
      - name: Wait for Localstack
        run: |
          timeout 60 sh -c 'until nc -z localhost 4566; do echo "Waiting for Localstack ..."; sleep 1; done'
        continue-on-error: true
      - name: Run test
        shell: bash
        run: ${{ inputs.test_command }}